# Generated by Django 2.2.3 on 2019-07-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0002_auto_20190727_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_list', models.CharField(max_length=250, null=None)),
            ],
        ),
    ]
