# Generated by Django 2.2.3 on 2019-07-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0003_wrapper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wrapper',
        ),
    ]
