# Generated by Django 2.2.3 on 2019-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0004_delete_wrapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-prod'),
            preserve_default=False,
        ),
    ]
