# Generated by Django 2.2.3 on 2019-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0005_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
