# Generated by Django 2.2.3 on 2019-07-31 12:52

from django.db import migrations, models
import dshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0010_auto_20190727_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=dshop.models.image_folder),
        ),
    ]
