# Generated by Django 2.2.3 on 2019-08-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0015_auto_20190801_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category']},
        ),
    ]
